### ISSUE TITLE
Mac OS X Compatibility

### ISSUE THREAD

**Issue by seagoj** [Jarkore/Feednix#16]
I had to install libjsoncpp, which I did through homebrew (0.6.0-rc2), to get this far.

```bash
$ ./autogen.sh && ./configure
```
completes successfully, but make exits with the following error:

```bash
$ make
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in src
g++ -DHAVE_CONFIG_H -I. -I..  -DDEBUG -std=c++11 -Wall    -g -O2 -MT feednix-FeedlyProvider.o -MD -MP -MF .deps/feednix-FeedlyProvider.Tpo -c -o feednix-FeedlyProvider.o `test -f 'FeedlyProvider.cpp' || echo './'`FeedlyProvider.cpp
FeedlyProvider.cpp:96:17: warning: comparison between NULL and non-pointer ('std::ifstream' (aka 'basic_ifstream<char>') and NULL)
      [-Wnull-arithmetic]
        if(data == NULL || curl_res != CURLE_OK || !parsingSuccesful){
           ~~~~ ^  ~~~~
FeedlyProvider.cpp:96:17: error: invalid operands to binary expression ('std::ifstream' (aka 'basic_ifstream<char>') and 'long')
        if(data == NULL || curl_res != CURLE_OK || !parsingSuccesful){
           ~~~~ ^  ~~~~
FeedlyProvider.cpp:142:17: warning: comparison between NULL and non-pointer ('std::ifstream' (aka 'basic_ifstream<char>') and NULL)
      [-Wnull-arithmetic]
        if(data == NULL || curl_res != CURLE_OK || !parsingSuccesful){
           ~~~~ ^  ~~~~
FeedlyProvider.cpp:142:17: error: invalid operands to binary expression ('std::ifstream' (aka 'basic_ifstream<char>') and 'long')
        if(data == NULL || curl_res != CURLE_OK || !parsingSuccesful){
           ~~~~ ^  ~~~~
FeedlyProvider.cpp:503:23: warning: comparison between NULL and non-pointer ('std::ofstream' (aka 'basic_ofstream<char>') and NULL)
      [-Wnull-arithmetic]
        if(log_stream != NULL && log_stream.is_open())
           ~~~~~~~~~~ ^  ~~~~
FeedlyProvider.cpp:503:23: error: invalid operands to binary expression ('std::ofstream' (aka 'basic_ofstream<char>') and 'long')
        if(log_stream != NULL && log_stream.is_open())
           ~~~~~~~~~~ ^  ~~~~
3 warnings and 3 errors generated.
make[2]: *** [feednix-FeedlyProvider.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

I realize Mac compatibility is likely not a priority, but I was hoping you could point me in a direction.

**Comment by Jarkore** [comment]
I think I have fixed the issue but since I don't own I mac I am unable to test it. Would you please pull the new code and see if the fix works?

Thanks

**Comment by seagoj** [comment]
That cut down on some of it, but I'm still getting the following:

```bash
$ make
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in src
g++ -DHAVE_CONFIG_H -I. -I..  -DDEBUG -std=c++11 -Wall    -g -O2 -MT feednix-FeedlyProvider.o -MD -MP -MF .deps/feednix-FeedlyProvider.Tpo -c -o feednix-FeedlyProvider.o `test -f 'FeedlyProvider.cpp' || echo './'`FeedlyProvider.cpp
FeedlyProvider.cpp:503:23: warning: comparison between NULL and non-pointer ('std::ofstream' (aka 'basic_ofstream<char>') and NULL) [-Wnull-arithmetic]
        if(log_stream != NULL && log_stream.is_open())
           ~~~~~~~~~~ ^  ~~~~
FeedlyProvider.cpp:503:23: error: invalid operands to binary expression ('std::ofstream' (aka 'basic_ofstream<char>') and 'long')
        if(log_stream != NULL && log_stream.is_open())
           ~~~~~~~~~~ ^  ~~~~
1 warning and 1 error generated.
make[2]: *** [feednix-FeedlyProvider.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by Jarkore** [comment]
A yes I must apologize. This is an issue with C++11 and streams. Strangely enough, compiling feednix with gcc and C++11 does not raise these issues despite that it should.

**Comment by seagoj** [comment]
Is that something that's fixable or is it a dead end?

**Comment by Jarkore** [comment]
Of course its just that I was explaining the issue, I will be looking at the code in the next few days and refactor it but worry not I will push a quick patch to hopefully fix this issue.

**Comment by Jarkore** [comment]
I do believe that all errors have been fixed so if you already haven't tried the latests changes you could try now.

**Comment by justmytwospence** [comment]
@seagoj I'm still getting `'json/json.h' file not found`. How did you install libjsoncpp precisely?

**Comment by Jarkore** [comment]
Could you please run this on the command line and tell me its output?

`cd "/usr/include/$(ls | grep -x 'json' | tr -d '\n')" && ls`

**Comment by justmytwospence** [comment]
```
AssertMacros.h          apr-1              curl              fcntl.h         ifaddrs.h        libproc.h       mpool.h        os              ranlib.h          slapi-plugin.h  tclDecls.h         unctrl.h
Availability.h          ar.h               curses.h          fenv.h          inttypes.h       libunwind.h     nameser.h      panel.h         readline          spawn.h         tclPlatDecls.h     unistd.h
AvailabilityInternal.h  architecture       cxxabi.h          ffi             iso646.h         libxml2         nc_tparm.h     paths.h         readpassphrase.h  sqlite3.h       tclTomMath.h       unwind.h
AvailabilityMacros.h    arpa               db.h              fmtmsg.h        kern             libxslt         ncurses.h      pcap            regex.h           sqlite3ext.h    tclTomMathDecls.h  util.h
Block.h                 asl.h              default_pager     fnmatch.h       krb5             limits.h        ncurses_dll.h  pcap-bpf.h      removefile.h      stab.h          term.h             utime.h
CommonCrypto            assert.h           device            form.h          krb5.h           localcharset.h  ndbm.h         pcap-namedb.h   resolv.h          standards.h     term_entry.h       utmp.h
ConditionalMacros.h     bitstring.h        dirent.h          fsproperties.h  langinfo.h       locale.h        net            pcap.h          rpc               stdbool.h       termcap.h          utmpx.h
MacTypes.h              bootparams.h       disktab.h         fstab.h         launch.h         mach            net-snmp       pexpert         rpcsvc            stddef.h        termios.h          uuid
NSSystemDirectories.h   bsm                dispatch          fts.h           lber.h           mach-o          netdb.h        php             rune.h            stdint.h        tic.h              vfs
TargetConditionals.h    bzlib.h            dlfcn.h           ftw.h           lber_types.h     mach_debug      netinet        poll.h          runetype.h        stdio.h         tidy               vis.h
Xplugin.h               c++                dns.h             get_compat.h    ldap.h           machine         netinet6       printerdb.h     sandbox.h         stdlib.h        time.h             vproc.h
_locale.h               cache.h            dns_sd.h          gethostuuid.h   ldap_cdefs.h     malloc          netkey         printf.h        sasl              strhash.h       timeconv.h         wchar.h
_structs.h              cache_callbacks.h  dns_util.h        getopt.h        ldap_features.h  math.h          nfs            profile.h       sched.h           string.h        tk.h               wctype.h
_types                  checkint.h         dtrace.h          glob.h          ldap_schema.h    membership.h    nl_types.h     protocols       search.h          stringlist.h    tkDecls.h          wordexp.h
_types.h                com_err.h          editline          grp.h           ldap_utf8.h      memcached       nlist.h        pthread.h       secure            strings.h       tkIntXlibDecls.h   xar
_wctype.h               complex.h          err.h             gssapi          ldif.h           memory.h        notify.h       pthread_impl.h  security          struct.h        tkMacOSX.h         xlocale
_xlocale.h              copyfile.h         errno.h           gssapi.h        libc.h           menu.h          notify_keys.h  pthread_spis.h  semaphore.h       sys             tkPlatDecls.h      xlocale.h
aio.h                   cpio.h             eti.h             hfs             libcharset.h     miscfs          ntsid.h        pwd.h           servers           sysexits.h      ttyent.h           xpc
aliasdb.h               crt_externs.h      execinfo.h        histedit.h      libexslt         module.map      objc           python2.5       setjmp.h          syslog.h        tzfile.h           zconf.h
alloca.h                ctype.h            expat.h           i386            libgen.h         monetary.h      odmodule       python2.6       sgtty.h           tar.h           ucontext.h         zlib.h
apache2                 cups               expat_external.h  iconv.h         libkern          monitor.h       openssl        python2.7       signal.h          tcl.h           ulimit.h
```

**Comment by Jarkore** [comment]
I do not see the jsoncpp header files. Could you please confirm that you installed jsoncpp correctly?

**Comment by justmytwospence** [comment]
I thought I had installed it with homebrew (`brew install jsoncpp`), but that must not be right. Hopefully seagoj can shed some light.

**Comment by seagoj** [comment]
I'll take a look at this again today. It's been a while since I messed with it.

**Comment by justmytwospence** [comment]
Any insight into how you installed libjsoncpp?

**Comment by dlord781** [comment]
For what it is worth on this closed ticket I got around the json/json.h by doing the following:

```bash
$ brew install jsoncpp
$ sudo ln -s /usr/local/Cellar/jsoncpp/0.6.0-rc2/include/jsoncpp/json/ /usr/include/json
$ ./autogen.sh
$ ./configure
$ make
$ sudo make install
```

**Comment by Nx357** [comment]
After installing jsoncpp with homebre, it does not work. When I launch feednix : 

cp: /etc/xdg/feednix/config.json: No such file or directory
chmod: /Users/tralala/.config/feednix/config.json: No such file or directory
Aborted.

**Comment by Jarkore** [comment]
My apologies. This is a bug that I had not noticed. It should be all fixed on the latest code.

**Comment by Nx357** [comment]
Hi Jarkore, on the latest code I still have the issue when launching feednix : 
cp: /etc/xdg/feednix/config.json: No such file or directory
chmod: /Users/tralala/.config/feednix/config.json: No such file or directory

The two previous lines of my previous comment have disappeared.

**Comment by Jarkore** [comment]
Best thing to do make the directory:

mkdir -p $HOME/.config/feenidx

and cp config.json that is in the git repo into it.

I apologize for this. I never imagined that someone was going to use this other than me, more so someone using OS X.   xD

**Comment by jrcii** [comment]
I have had a really hard time getting make to build this on OS X. I definitely have jsoncpp installed, I have it symlinked to /usr/include/json and make still complains that it can't find the headers 
http://pastebin.com/MCq1Wzph

**Comment by Nx357** [comment]
@Jarkore : Thank you ! It works ! I rediscover the pleasure of CLI under OS X ;)

@jrcii : 
1. Uninstall jsoncpp with macport
sudo port -fp uninstall jsoncpp

and make sure you have removed json folder
cd /opt/local/include
rm -rf json

2. Make sure that you have removed the symbolic link under /usr/include/json : 
rm /usr/include/json 

3. Prefer Brew installation : thanks to @dlord781 
brew install jsoncpp
sudo ln -s /usr/local/Cellar/jsoncpp/0.6.0-rc2/include/jsoncpp/json/ /usr/include/json

Then create this : thanks to @Jarkore 
mkdir -p $HOME/.config/feenidx

and cp the config.json file from the feednidx repository here

Then : 
./autogen.sh
./configure
make
sudo make install

Have a lot of fun under OS X ;)

**Comment by nx357** [comment]
@Jarkore : Hello, I am facing a new issue with feednix.

1. When I enter o or O, nothing happen.
2. When I navigate between each post, the content is not display below

Maybe something is missing under mac OS X ?

**Comment by Jarkore** [comment]
Yes, to both preview on the pane and when pressing "o", it tries to use a program called w3m to extract the rendered plain html content. I am not sure if you can get this under OS X.

**Comment by jrcii** [comment]
w3m is available on homebrew and macports

**Comment by nx357** [comment]
@jrcii : w3m is already installed on my notebook
